# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      #v.gui = true
    end
  
    config.vm.define "centos" do |centos|
      centos.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      centos.vm.hostname = "centos"
      script_path = './scripts'
      config.vm.provision "shell" do |script|
      script.path = "#{script_path}/unit.sh"
    end
  end
end